<h1 style="text-align: center; font-family: Georgia, serif; letter-spacing: 6px; color: #fff; font-size: 2.8em; font-weight: 900; margin-bottom: 0;">
  PANDAS
</h1>
<p style="text-align: center; color: #7f8c8d; letter-spacing: 3px; font-size: 0.85em; margin-top: 6px;">
  NUMERICAL PYTHON  •  DATA SCIENCE SERIES
</p>
<hr style="border: none; height: 2px; background-color: #2c3e50; width: 50%; margin: 10px auto;">

In [1]:
import pandas as pd
import numpy as np

In [2]:
labels=['a','b','c']
my_list=[1,2,3]
arr=np.array([10,20,30])
d={1:10,2:20,3:30}
pd.Series(my_list)

0    1
1    2
2    3
dtype: int64

In [3]:
pd.Series(my_list,index=labels)

a    1
b    2
c    3
dtype: int64

In [4]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [5]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

<h2 style="text-align: center; font-family: Georgia, serif; letter-spacing: 3px; color: #fff; font-size: 1.6em; font-weight: 700; margin-bottom: 0;">
 Creating a Dataframe
</h2>
<hr style="border: none; height: 1px; background-color: #fff; width: 35%; margin: 6px auto;">

In [ ]:
data={
    'Name': ['John','Anna','Peter','Linda'],
    "Age":[15,16,17,18],
    "City":["London","Karachi","UK","Berlin"],
    "Salary":[65000,54000,23000,23200]
}
df=pd.DataFrame(data)

    Name  Age     City  Salary
0   John   15   London   65000
1   Anna   16  Karachi   54000
2  Peter   17       UK   23000
3  Linda   18   Berlin   23200

In [11]:
data=[
     ['John','Anna','Peter','Linda'],
    [15,16,17,18],
    ["London","Karachi","UK","Berlin"],
    [65000,54000,23000,23200]
]
df=pd.DataFrame(data)

columns=["Name","Age","City","Salary"]
df=pd.DataFrame(data,columns=columns)
print(df)

     Name      Age   City  Salary
0    John     Anna  Peter   Linda
1      15       16     17      18
2  London  Karachi     UK  Berlin
3   65000    54000  23000   23200

In [12]:
df['Name']

0      John
1        15
2    London
3     65000
Name: Name, dtype: object

In [15]:
df[['Name','City']]

     Name   City
0    John  Peter
1      15     17
2  London     UK
3   65000  23000

<h2 style="text-align: center; font-family: Georgia, serif; letter-spacing: 3px; color: #fff; font-size: 1.6em; font-weight: 700; margin-bottom: 0;">
 Creating new column
</h2>
<hr style="border: none; height: 1px; background-color: #fff; width: 35%; margin: 6px auto;">

In [16]:
df['Designation']=['Engineer','Doctor','Plumber','Engineer']

In [17]:
print(df)

     Name      Age   City  Salary Designation
0    John     Anna  Peter   Linda    Engineer
1      15       16     17      18      Doctor
2  London  Karachi     UK  Berlin     Plumber
3   65000    54000  23000   23200    Engineer

<h2 style="text-align: center; font-family: Georgia, serif; letter-spacing: 3px; color: #fff; font-size: 1.6em; font-weight: 700; margin-bottom: 0;">
 Deleting column
</h2>
<hr style="border: none; height: 1px; background-color: #fff; width: 35%; margin: 6px auto;">

In [19]:
df.drop("Designation",axis=1,inplace=True)

In [20]:
df

     Name      Age   City  Salary
0    John     Anna  Peter   Linda
1      15       16     17      18
2  London  Karachi     UK  Berlin
3   65000    54000  23000   23200

<h2 style="text-align: center; font-family: Georgia, serif; letter-spacing: 3px; color: #fff; font-size: 1.6em; font-weight: 700; margin-bottom: 0;">
 Selecting rows
</h2>
<hr style="border: none; height: 1px; background-color: #fff; width: 35%; margin: 6px auto;">

In [23]:
df.loc[[0,1]]

   Name   Age   City Salary
0  John  Anna  Peter  Linda
1    15    16     17     18

<h2 style="text-align: center; font-family: Georgia, serif; letter-spacing: 3px; color: #fff; font-size: 1.6em; font-weight: 700; margin-bottom: 0;">
 Selecting rows and columns at same time
</h2>
<hr style="border: none; height: 1px; background-color: #fff; width: 35%; margin: 6px auto;">

In [25]:
df.loc[[0,1]][['City','Salary']]

    City Salary
0  Peter  Linda
1     17     18