<h1 style="text-align: center; font-family: Georgia, serif; letter-spacing: 6px; color: #fff; font-size: 2.8em; font-weight: 900; margin-bottom: 0;">
  PANDAS
</h1>
<p style="text-align: center; color: #7f8c8d; letter-spacing: 3px; font-size: 0.85em; margin-top: 6px;">
  NUMERICAL PYTHON  •  DATA SCIENCE SERIES
</p>
<hr style="border: none; height: 2px; background-color: #2c3e50; width: 50%; margin: 10px auto;">

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
labels=['a','b','c']
my_list=[1,2,3]
arr=np.array([10,20,30])
d={1:10,2:20,3:30}
pd.Series(my_list)

In [ ]:
pd.Series(my_list,index=labels)

In [ ]:
pd.Series(arr)

In [ ]:
pd.Series(d)

<h2 style="text-align: center; font-family: Georgia, serif; letter-spacing: 3px; color: #fff; font-size: 1.6em; font-weight: 700; margin-bottom: 0;">
 Creating a Dataframe
</h2>
<hr style="border: none; height: 1px; background-color: #fff; width: 35%; margin: 6px auto;">

In [ ]:
data={
    'Name': ['John','Anna','Peter','Linda'],
    "Age":[15,16,17,18],
    "City":["London","Karachi","UK","Berlin"],
    "Salary":[65000,54000,23000,23200]
}
df=pd.DataFrame(data)

In [ ]:
data=[
     ['John','Anna','Peter','Linda'],
    [15,16,17,18],
    ["London","Karachi","UK","Berlin"],
    [65000,54000,23000,23200]
]
df=pd.DataFrame(data)

columns=["Name","Age","City","Salary"]
df=pd.DataFrame(data,columns=columns)
print(df)

In [ ]:
df['Name']

In [ ]:
df[['Name','City']]

<h2 style="text-align: center; font-family: Georgia, serif; letter-spacing: 3px; color: #fff; font-size: 1.6em; font-weight: 700; margin-bottom: 0;">
 Creating new column
</h2>
<hr style="border: none; height: 1px; background-color: #fff; width: 35%; margin: 6px auto;">

In [ ]:
df['Designation']=['Engineer','Doctor','Plumber','Engineer']

In [ ]:
print(df)

<h2 style="text-align: center; font-family: Georgia, serif; letter-spacing: 3px; color: #fff; font-size: 1.6em; font-weight: 700; margin-bottom: 0;">
 Deleting column
</h2>
<hr style="border: none; height: 1px; background-color: #fff; width: 35%; margin: 6px auto;">

In [ ]:
df.drop("Designation",axis=1,inplace=True)

In [ ]:
df

<h2 style="text-align: center; font-family: Georgia, serif; letter-spacing: 3px; color: #fff; font-size: 1.6em; font-weight: 700; margin-bottom: 0;">
 Selecting rows
</h2>
<hr style="border: none; height: 1px; background-color: #fff; width: 35%; margin: 6px auto;">

In [ ]:
df.loc[[0,1]]

<h2 style="text-align: center; font-family: Georgia, serif; letter-spacing: 3px; color: #fff; font-size: 1.6em; font-weight: 700; margin-bottom: 0;">
 Selecting rows and columns at same time
</h2>
<hr style="border: none; height: 1px; background-color: #fff; width: 35%; margin: 6px auto;">

In [ ]:
df.loc[[0,1]][['City','Salary']]

In [ ]:
df.loc[[2,3]][['Name','Age']]

<h2 style="text-align: center; font-family: Georgia, serif; letter-spacing: 3px; color: #fff; font-size: 1.6em; font-weight: 700; margin-bottom: 0;">
 Conditional Selection
</h2>
<hr style="border: none; height: 1px; background-color: #fff; width: 35%; margin: 6px auto;">

In [12]:
#I want to select those people whose age is above 15
df[df['Age']>15]

#I want to select those people whose age is above 15 and they live in UK
df[(df['Age']>15) & (df['City']=="UK")]

    Name  Age City  Salary
2  Peter   17   UK   23000

<h2 style="text-align: center; font-family: Georgia, serif; letter-spacing: 3px; color: #fff; font-size: 1.6em; font-weight: 700; margin-bottom: 0;">
Finding Missing Data
</h2>
<hr style="border: none; height: 1px; background-color: #fff; width: 35%; margin: 6px auto;">

In [13]:
import pandas as pd
import numpy as np

In [14]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)
print(df)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [15]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [16]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [17]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [18]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [ ]:
df.dropna(thresh=3)# this mean that atleast we should have 3 non null values in a row if the doesnot have so it will be removed

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [20]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

<h2 style="text-align: center; font-family: Georgia, serif; letter-spacing: 3px; color: #fff; font-size: 1.6em; font-weight: 700; margin-bottom: 0;">
Filling the Missing Data
</h2>
<hr style="border: none; height: 1px; background-color: #fff; width: 35%; margin: 6px auto;">

In [21]:
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

<h2 style="text-align: center; font-family: Georgia, serif; letter-spacing: 3px; color: #fff; font-size: 1.6em; font-weight: 700; margin-bottom: 0;">
Fill missing values with different values for each column
</h2>
<hr style="border: none; height: 1px; background-color: #fff; width: 35%; margin: 6px auto;">

In [22]:
values={"A":0,"B":100,"C":300,"D":400}
df.fillna(value=values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0